### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by IRus** [Ibydy/myservice#1]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/joda/Desktop/myservice/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'myservice'.
> Could not find method testCompile() for arguments [junit:junit:4.4] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@6e225c34.

**Comment by Ibydy** [comment]
already decieded
